#!/bin/zsh

output_file="/opt/barny/modules/cpu_freq.tmp"
final_file="/opt/barny/modules/cpu_freq"

while true; do
  p_sum=0
  for cpu in {0..7}; do
    freq=$(cat /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_cur_freq) 
    freq=$(echo "scale=3; $freq / 1000000" | bc)
    p_sum=$(echo "scale=3; $p_sum + $freq" | bc)
  done
  p_avg=$(echo "scale=3; $p_sum / 8" | bc)

  e_sum=0
  for cpu in {8..19}; do
    freq=$(cat /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_cur_freq) 
    freq=$(echo "scale=3; $freq / 1000000" | bc)
    e_sum=$(echo "scale=3; $e_sum + $freq" | bc)
  done
  e_avg=$(echo "scale=3; $e_sum / 12" | bc)
  
  echo "P: $p_avg E: $e_avg" > "$output_file"

  mv -f "$output_file" "$final_file"

  sleep 2
done
