#!/bin/zsh

output_file="/opt/misc/frequency.tmp"
final_file="/opt/misc/frequency"

while true; do
        E1=$(sudo cat /sys/class/powercap/intel-rapl:0/energy_uj) 
        sleep 1
        
        E2=$(sudo cat /sys/class/powercap/intel-rapl:0/energy_uj)
        power=$(echo "scale=2; ($E2-$E1)/1000000" | bc)
        
        echo "PWR: $power" > "$output_file"
        
        mv -f "$output_file" "$final_file"
        
        sleep 2
done
